#pragma once
#include <stdint.h>

// Claude logo placeholder — 40×40 px RGB565
// Simple "C" letterform in Anthropic orange on black background.
// Replace with official logo asset if/when available.

#define LOGO_W 40
#define LOGO_H 40

static const uint16_t logo_pixels[LOGO_W * LOGO_H] = {
    // Row-major, RGB565. Generated as a simple orange circle-with-gap (C shape).
    // 0x0000 = black (transparent), 0xDB6B = Anthropic orange
    #define BK 0x0000
    #define OR 0xDB6B
    #define D1 0xAD55  // dark orange
    BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,
    BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,BK,BK,
    BK,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,BK,
    BK,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,BK,
    OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,
    OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,
    BK,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,BK,
    BK,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,BK,
    BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,BK,BK,BK,BK,BK,BK,BK,
    BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,
    BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,BK,BK,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,OR,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,BK,
    #undef BK
    #undef OR
    #undef D1
};
