[env:claudeoclock_amoled_216]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
upload_speed = 921600
monitor_speed = 115200

build_src_filter =
    +<*>
    -<boards/>
    +<boards/waveshare_amoled_216/>

build_flags =
    -DBOARD_CLAUDEOCLOCK_AMOLED_216
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DXPOWERS_CHIP_AXP2101
    -DLV_CONF_SKIP
    -DLV_COLOR_DEPTH=16
    -DLV_USE_LOG=0
    -DLV_USE_BAR=1
    -DLV_USE_LABEL=1
    -DLV_USE_ARC=1
    -DLV_USE_BTN=1
    -DLV_USE_LINE=1
    -DLV_USE_OBJ=1
    -DLV_USE_IMG=1
    -DLV_USE_IMAGE=1
    -DLV_USE_ANIMIMG=0
    -DLV_TICK_CUSTOM=1
    -DLV_USE_SNAPSHOT=1
    -DLV_FONT_MONTSERRAT_18=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_28=1
    -DLV_FONT_MONTSERRAT_52=1

lib_deps =
    moononournation/GFX Library for Arduino@^1.5.6
    lewisxhe/SensorLib@^0.2.6
    lewisxhe/XPowersLib@^0.2.7
    lvgl/lvgl@^9.2.0
    bblanchon/ArduinoJson@^7.0.0
    ricmoo/QRCode@^0.0.1
